---
branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
  - name: dev
    prerelease: true
plugins:
  - - "semantic-release-gitmoji"
    - releaseRules:
        major:
          - ":boom:"
        minor:
          - ":sparkles:"
        patch:
          - ":bug:"
          - ":ambulance:"
          - ":lock:"
          - ":pencil2:"
          - ":adhesive_bandage:"
          - ":art:"
          - ":zap:"
          - ":fire:"
          - ":lipstick:"
          - ":arrow_up:"
          - ":arrow_down:"
          - ":heavy_plus_sign:"
          - ":heavy_minus_sign:"
          - ":recycle:"
          - ":truck:"
          - ":bento:"
          - ":alien:"
          - ":speech_balloon:"
          - ":card_file_box:"
          - ":loud_sound:"
          - ":mute:"
          - ":children_crossing:"
          - ":building_construction:"
          - ":iphone:"
          - ":dizzy:"
          - ":passport_control:"
          - ":necktie:"
          - ":thread:"
          - ":stethoscope:"
          - ":safety_vest:"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: "npx prettier --write CHANGELOG.md"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: "🔖 Update `package.json` to `${nextRelease.version}` [skip release]\n\n${nextRelease.notes}"
