---
branches:
  - main
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true
  - name: dev
    prerelease: true
plugins:
  - "semantic-release-gitmoji"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - - "@semantic-release/exec"
    - prepareCmd: "npx prettier --write CHANGELOG.md"
  - "@semantic-release/github"
  - - "@semantic-release/git"
    - assets:
        - CHANGELOG.md
        - package.json
      message: "🔖 Update `package.json` to `${nextRelease.version}` [skip release]\n\n${nextRelease.notes}"
