# yaml-language-server: $schema=https://json-schema.org/draft-07/schema
$schema: http://json-schema.org/draft-07/schema
$ref: "#/components/schemas/scraper-specification-settings"
$id: io/github/lengors/protoscout/domain/scrapers/specifications/models/006-scraper-specification-settings.yml

components:
  schemas:
    scraper-specification-settings:
      title: Scraper specification's settings.
      description: Scraper specification settings definition.

      javaType: io.github.lengors.protoscout.domain.scrapers.specifications.models.ScraperSpecificationSettings
      javaInterfaces:
        - java.io.Serializable

      type: object
      additionalProperties: false

      required:
        - defaults
        - locale
        - timezone

      properties:
        defaults:
          $ref: 004-scraper-specification-defaults.yml#/components/schemas/scraper-specification-defaults

        locale:
          $ref: 001-scraper-specification-expression.yml#/components/schemas/scraper-specification-expression

        timezone:
          $ref: 001-scraper-specification-expression.yml#/components/schemas/scraper-specification-expression

        certificates:
          type: array
          title: Scraper's certificates.
          description: List of certificates to be used by scraper.
          items:
            type: string
            title: Scraper's certificate.
            description: Certificate for scraper.

        requirements:
          type: array
          title: Scraper specification's requirements.
          description: List of required custom input for scraper.
          items:
            $ref: 001-scraper-specification-requirement.yml#/components/schemas/scraper-specification-requirement
