---
name: Validate pull request

on:
  pull_request:
    branches:
      - main
      - beta
      - alpha
      - dev

jobs:
  check-style:
    name: Check code style
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Perform style check
        run: npx prettier --check .

  validate-json-schemas:
    name: Validate JSON schemas
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Perform style check
        run: npm run lint
